# Generated by Django 3.2.6 on 2021-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210817_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_form',
            old_name='visitor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact_form',
            old_name='visitor',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact_form',
            old_name='visitor_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='contact_form',
            name='visitor_message',
        ),
        migrations.AddField(
            model_name='contact_form',
            name='message',
            field=models.TextField(default='', help_text='Enter Your Message Here'),
            preserve_default=False,
        ),
    ]
